version: "3"

services:
    www:
        build: .
        restart: always
        ports: 
            - '5000:80'
        volumes:
            - ./www:/var/www/html
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        ports:
            - '3307:3306'
        environment: 
            MYSQL_DATABASE: database
            MYSQL_USER: usuario
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 12345
        volumes: 
            - db_data:/var/lib/mysql
        networks:
            - default
volumes:
    db_data: